//#### GENERATED BY CODEX ####
//#### GENERATED BY CODEX ####
//#### GENERATED BY CODEX ####
//#### VERIFIED BY HUMAN ####
//#### VERIFIED BY HUMAN ####
//#### VERIFIED BY HUMAN ####

#pragma once

// Set this flag to true to start the OTA hotspot and captive portal.
// The module consumes the flag and resets it to false automatically.
extern bool xStartOTAHotspot;
extern bool xOTAActive;

// OTA_MANIFEST_URL must return JSON in this form:
// {"name":"SOL","version":"1.0.1","url":"https://.../firmware.bin","md5":"optional"}
void LightboxUISetup();
void LightboxUILoop();
